[package]
name = "secpass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.15.1"
iced = { version = "0.12.1", features = ["image", "debug" ] }
sqlite = "0.36.0"
